
package base_de_donnée;
import Application.Parametre;
import Application.ResultSetTableModel;
import Application.BDD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Cachier extends javax.swing.JFrame {

     //déclaration
    ResultSet rs;
    BDD db;
    int old, dec,now;
    
    public Cachier() {
        db = new BDD(new Parametre().HOST_DB, new Parametre().USERNAME_DB,new Parametre().PASSWORD_DB, new Parametre().IPHOST,new Parametre().PORT);
        initComponents();
        table();
        jam();
    }
     public final void table(){
            String a[] = {"code_produit","reference","designation","rangement","fournisseur","remise","prix","stock"};
            rs = db.querySelect(a,"produit");
            table_cachier.setModel(new ResultSetTableModel(rs));
            
        }
     
     public void importer(){
         String colon [] = {"num_facture","code_produit","reference","prix_vente","stock_sortie","subtotal"};
         rs = db.forSelectCommand(colon, "vente","num_facture='" + txt_fac.getText() + "'");
         table_vente.setModel(new ResultSetTableModel(rs));
     }
     
     //
     public final void jam(){
         Date s = new Date();
         SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
         SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
         lbl2.setText(jam.format(s));
         lbl1.setText(tgl.format(s));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cachier = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        box_cher = new javax.swing.JComboBox();
        txt_cher = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_sto = new javax.swing.JTextField();
        txt_cod = new javax.swing.JTextField();
        txt_p = new javax.swing.JTextField();
        txt_ref = new javax.swing.JTextField();
        txt_nou = new javax.swing.JTextField();
        txt_ran = new javax.swing.JTextField();
        txt_remise = new javax.swing.JTextField();
        txt_four = new javax.swing.JTextField();
        lbltot1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_vente = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbltot2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_pay = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_fac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1060, 1000));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        table_cachier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "code_produit", "reference", "designation", "rangement", "fournisseur", "remise", "prix", "stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_cachier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_cachierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_cachier);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(12, 80, 1000, 120);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Cachier");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 210);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Recherche par catégorie :");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(330, 10, 320, 50);

        box_cher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id", "code_produit", "reference", "designation", "rangement", "fournisseur", "remise", "prix", "stock" }));
        box_cher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_cherActionPerformed(evt);
            }
        });
        jPanel2.add(box_cher);
        box_cher.setBounds(621, 90, 150, 30);

        txt_cher.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txt_cher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cherActionPerformed(evt);
            }
        });
        jPanel2.add(txt_cher);
        txt_cher.setBounds(800, 90, 90, 28);

        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton5.setText("Recherche");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(910, 90, 111, 31);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Code produit :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 130, 108, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Reference :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(290, 130, 86, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Nouveau prix :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(480, 180, 120, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setText("Rangement :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(490, 130, 97, 22);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setText("Fournisseur:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(700, 130, 98, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("Remise :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(310, 180, 66, 22);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setText("Prix :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(80, 180, 43, 22);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel12.setText("Stock de sortie:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(700, 180, 130, 22);

        txt_sto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stoActionPerformed(evt);
            }
        });
        txt_sto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_stoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_sto);
        txt_sto.setBounds(830, 180, 80, 22);

        txt_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codKeyReleased(evt);
            }
        });
        jPanel2.add(txt_cod);
        txt_cod.setBounds(140, 130, 80, 22);

        txt_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pActionPerformed(evt);
            }
        });
        jPanel2.add(txt_p);
        txt_p.setBounds(140, 180, 80, 22);

        txt_ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_refActionPerformed(evt);
            }
        });
        jPanel2.add(txt_ref);
        txt_ref.setBounds(390, 130, 80, 22);

        txt_nou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nouActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nou);
        txt_nou.setBounds(610, 180, 80, 22);

        txt_ran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ranActionPerformed(evt);
            }
        });
        jPanel2.add(txt_ran);
        txt_ran.setBounds(600, 130, 80, 22);

        txt_remise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remiseActionPerformed(evt);
            }
        });
        jPanel2.add(txt_remise);
        txt_remise.setBounds(390, 180, 80, 22);

        txt_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fourActionPerformed(evt);
            }
        });
        jPanel2.add(txt_four);
        txt_four.setBounds(810, 130, 80, 22);

        lbltot1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot1.setText("0");
        jPanel2.add(lbltot1);
        lbltot1.setBounds(830, 220, 140, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("RP :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(760, 220, 50, 22);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton4.setText("Ajouter produit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(760, 250, 260, 30);

        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(lbl2);
        lbl2.setBounds(30, 20, 190, 30);

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl1KeyReleased(evt);
            }
        });
        jPanel2.add(lbl1);
        lbl1.setBounds(720, 20, 260, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 210, 1030, 290);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(1020, 430));
        jPanel3.setLayout(null);

        table_vente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_produit", "reference", "prix_vente", "stock_sortie", "subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_vente);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 130, 1010, 100);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(930, 90, 95, 25);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("Rechercher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(820, 90, 100, 25);

        lbltot2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbltot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot2.setText("0");
        jPanel3.add(lbltot2);
        lbltot2.setBounds(890, 250, 130, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Total ");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(750, 250, 46, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setText("Payé aprés :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(800, 290, 120, 22);

        txt_pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_payActionPerformed(evt);
            }
        });
        jPanel3.add(txt_pay);
        txt_pay.setBounds(920, 290, 100, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel17.setText("Cash :");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(620, 290, 70, 22);

        txt_cash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cashActionPerformed(evt);
            }
        });
        txt_cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cashKeyReleased(evt);
            }
        });
        jPanel3.add(txt_cash);
        txt_cash.setBounds(690, 290, 100, 23);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(860, 370, 160, 30);

        jButton6.setBackground(new java.awt.Color(0, 153, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton6.setText("Imprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(860, 330, 160, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("RP :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(830, 250, 34, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Numéro facture :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(590, 90, 150, 22);

        txt_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facActionPerformed(evt);
            }
        });
        jPanel3.add(txt_fac);
        txt_fac.setBounds(730, 90, 80, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 500, 1030, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(txt_cher.getText().equals("")){ //si le textfield de la recherche est vide  ,le programme va afficher le message ci dessous
            JOptionPane.showMessageDialog(this, "Taper quelque chose !!");
        }else{
            if(box_cher.getSelectedItem().equals("id")){
                rs = db.querySelectAll("vente","id LIKE '%" + txt_cher.getText() + "%' ");
                table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("code_produit")){
                rs = db.querySelectAll("vente", "code_produit LIKE '%" + txt_cher.getText() + "%' ");
                table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("reference")){
                rs = db.querySelectAll("vente", "reference LIKE '%" + txt_cher.getText() + "%' ");
                table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("designation")){
                rs = db.querySelectAll("vente", "designation LIKE '%" + txt_cher.getText() + "%' ");
                table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("rangement")){
                rs = db.querySelectAll("vente", "rangement LIKE '%" + txt_cher.getText() + "%' ");
                table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("fournisseur")){
                rs = db.querySelectAll("vente", "fournisseur LIKE '%" + txt_cher.getText() + "%' ");
               table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("remise")){
                rs = db.querySelectAll("vente", "remise LIKE '%" + txt_cher.getText() + "%' ");
                table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("prix")){
                rs = db.querySelectAll("vente", "prix LIKE '%" + txt_cher.getText() + "%' ");
                table_cachier.setModel(new ResultSetTableModel(rs));
            }else if (box_cher.getSelectedItem().equals("stock")){
                rs = db.querySelectAll("vente", "stock LIKE '%" + txt_cher.getText() + "%' ");
               table_cachier.setModel(new ResultSetTableModel(rs));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void box_cherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_cherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_cherActionPerformed

    private void txt_stoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stoActionPerformed

    private void txt_refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_refActionPerformed

    private void txt_nouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nouActionPerformed

    private void txt_ranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ranActionPerformed

    private void txt_remiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remiseActionPerformed

    private void txt_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fourActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String invoice = txt_fac.getText();
     if (JOptionPane.showConfirmDialog(this, "est ce que tu es sure que tu veux supprimer","attention",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
         db.queryDelete("vente","num_facture=" + invoice);
     }else {
         return;
     }
     importer();
     total();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       importer();
       total();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cashActionPerformed

    private void txt_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_payActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(txt_cod.getText().equals("") || txt_ref.getText().equals("") || txt_ran.getText().equals("") || 
               txt_four.getText().equals("") || txt_p.getText().equals("") || txt_nou.getText().equals("") || txt_remise.getText().equals("")
                       || txt_sto.getText().equals("")){
        JOptionPane.showMessageDialog(this, "SVP entrer vos données !!");
    }else if(txt_fac.getText().equals("")){
        JOptionPane.showMessageDialog(this,"SVP entrer le numéro facture !!");
    }
    else {
        
              
            
             
            String colon [] = {"num_facture","code_produit","reference","prix_vente","stock_sortie","subtotal"};
            String [] isi = {txt_fac.getText(), txt_cod.getText(),txt_ref.getText(),txt_nou.getText(),txt_sto.getText(),lbltot1.getText()};
            System.out.println(db.queryInsert("vente", colon, isi));
             
              try {
             if(!test_stock()) {
            JOptionPane.showMessageDialog(this, "le stock est limité");
            
            }else{
            def(); //true
            table(); //true
            }
             } catch (SQLException e) {
            Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE,null,e);
            System.err.println("\n" + e);
            }
            subtotal();
            importer();
            total();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       recu d = new recu();
       d.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_stoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stoKeyReleased
      subtotal();
    }//GEN-LAST:event_txt_stoKeyReleased

    private void txt_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id = String.valueOf(table_vente.getValueAt(table_vente.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this,"tu es sure que tu veux suprimer ?", "attention!!",JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION){
            db.queryDelete("vente", "id=" + id);
        }else {
            return;
        }
        importer();
        table();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_cashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cashKeyReleased
       payaprés();
    }//GEN-LAST:event_txt_cashKeyReleased

    private void txt_cherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cherActionPerformed

    private void table_cachierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_cachierMouseClicked
        txt_cod.setText(String.valueOf(table_cachier.getValueAt(table_cachier.getSelectedRow(),0)));
        txt_ref.setText(String.valueOf(table_cachier.getValueAt(table_cachier.getSelectedRow(),1)));
        txt_ran.setText(String.valueOf(table_cachier.getValueAt(table_cachier.getSelectedRow(),3)));
        txt_four.setText(String.valueOf(table_cachier.getValueAt(table_cachier.getSelectedRow(),4)));
        txt_remise.setText(String.valueOf(table_cachier.getValueAt(table_cachier.getSelectedRow(),5)));
        txt_p.setText(String.valueOf(table_cachier.getValueAt(table_cachier.getSelectedRow(),6)));
        cout();
    }//GEN-LAST:event_table_cachierMouseClicked

    private void lbl1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl1KeyPressed

    private void lbl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl1KeyReleased

    private void txt_codKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codKeyReleased

    private void txt_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_facActionPerformed

    //fonction qui calcule le total
    public void subtotal(){
        double a = Double.parseDouble(txt_nou.getText());
        double b = Double.parseDouble(txt_sto.getText());
        double c = a * b;
        lbltot1.setText(String.valueOf(c));
    }
    
    //fonction qui compare le nombre de produit pour le stock de sortie au stock produit initial
    public boolean test_stock() throws SQLException{
        boolean teststock;
        rs = db.querySelectAll("produit","code_produit='" + txt_cod.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
            
        }dec = Integer.parseInt(txt_sto.getText());
        if (old <dec) {
            teststock = false;
        }else {
            teststock = true;
        }
        return teststock;
    }
    
    //fonction qui fait la mise à jour du stock
    public void def() throws SQLException {
        rs = db.querySelectAll("produit","code_produit='" + txt_cod.getText() + "'");
        while (rs.next()){
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txt_sto.getText());
        now = old - dec;
        String nv_stock = Integer.toString(now);
        
        String a = String.valueOf(nv_stock);
        String[] colon = {"stock"};
        String[] isi = {a};
        System.out.println(db.queryUpdate("produit", colon, isi, "code_produit='" + txt_cod.getText() + "'"));
    }
    
    //
    public void total(){
        rs = db.exécutionQuery("SELECT SUM(subtotal) as subtotal FROM vente WHERE num_facture = '" + txt_fac.getText() + "'");
        try {
            rs.next();
            lbltot2.setText(rs.getString("subtotal"));
        } catch (SQLException ex) {
            Logger.getLogger(Cachier.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    public void payaprés(){
        int a = Integer.parseInt(lbltot2.getText());
        int b = Integer.parseInt(txt_cash.getText());
        int c = b - a;
        txt_pay.setText(Integer.toString(c));
        
    }
    
    //
    public void cout(){
        double a = Double.parseDouble(txt_p.getText());
        double b = Double.parseDouble(txt_remise.getText());
        double c = a - a * (b/100);
       txt_nou.setText(String.valueOf(c));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cachier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cachier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox box_cher;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbl1;
    public static javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbltot1;
    public static javax.swing.JLabel lbltot2;
    private javax.swing.JTable table_cachier;
    private javax.swing.JTable table_vente;
    public static javax.swing.JTextField txt_cash;
    private javax.swing.JTextField txt_cher;
    private javax.swing.JTextField txt_cod;
    public static javax.swing.JTextField txt_fac;
    private javax.swing.JTextField txt_four;
    private javax.swing.JTextField txt_nou;
    private javax.swing.JTextField txt_p;
    public static javax.swing.JTextField txt_pay;
    private javax.swing.JTextField txt_ran;
    private javax.swing.JTextField txt_ref;
    private javax.swing.JTextField txt_remise;
    private javax.swing.JTextField txt_sto;
    // End of variables declaration//GEN-END:variables
}
